name: elearning_management_app
description: E-learning Management Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # HTTP requests for chatbot
  http: ^1.2.0
  # Supabase for backend
  supabase_flutter: ^2.5.0
  flutter_markdown: ^0.6.14  # Required for rich text
  url_launcher: ^6.2.5       # Required for opening attachments
  file_saver: ^0.2.0
  
  # Local database
  sqflite: ^2.3.0
  path: ^1.9.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  path_provider: ^2.1.5

  # State management
  provider: ^6.1.1
  
  # UI components
  google_fonts: ^6.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  fl_chart: ^1.1.1
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  csv: ^6.0.0
  file_picker: ^10.3.3
  badges: ^3.1.2
  universal_html: ^2.2.4

  collection: ^1.19.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_ce_generator: ^1.10.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
